#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 26 16:00:07 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 56c750d059d04eee838fb9509fa6b21e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_circuitsTask1_behav xil_defaultlib.tb_circuitsTask1 xil_defaultlib.glbl -log elaborate.log"
xelab -wto 56c750d059d04eee838fb9509fa6b21e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_circuitsTask1_behav xil_defaultlib.tb_circuitsTask1 xil_defaultlib.glbl -log elaborate.log

